version: "3.3"
services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: auth_api
    ports:
      - 9191:3000
    environment:
      - DB_NAME=auth
      - DB_HOST=auth_db
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - DB_PORT=3306
      - REDIS_HOST=auth_redis
      - REDIS_PASSWORD=p4ssw0rd
      - REDIS_PORT=6379
    volumes:
      - ./:/app
    networks:
      - dev

  auth_db:
    image: mysql:8.0
    container_name: auth_db
    command: mysqld --user=root
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=auth
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
    networks:
      - dev


  auth_redis:
    image: redis:6.2.5-alpine
    container_name: auth_redis
    restart: unless-stopped
    environment:
      REDIS_PASSWORD: p4ssw0rd
    command: redis-server --requirepass p4ssw0rd
    # volumes:
      # - redisserverdata:/data
    tty: true
    ports:
      - 6399:6379
    networks:
      - dev

networks:
  dev:
